[package]
name = "paygate-kafkabus"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
anyhow = { workspace = true }
async-trait = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }

[dependencies.rdkafka]
version = "0.37"
default-features = false
features = ["cmake-build", "tokio", "libz"]
