//! `create_refund` and `complete_refund` — the two writes behind
//! `POST /payments/{id}/refunds` and its automatic, duplicate-payment
//! counterpart (`spec.md`, "Refunds"; "When the customer pays twice").
//!
//! Split in two, rather than one function that also calls the provider,
//! because a refund is "the one call paygate makes to a provider and waits
//! for" (`spec.md`, "Refunds") — and the row lock that keeps four racing
//! refunds from ever summing past the charge has to be held for the
//! duration of that call, which an `async` HTTP request inside an open
//! transaction cannot safely be asked to do at this crate's boundary. So:
//!
//! - [`create_refund`] holds the lock just long enough to check the request
//!   against `amount - amount_refunded` and, if it is legal, RESERVE it —
//!   `amount_refunded` is bumped immediately, before the provider is ever
//!   asked, which is what makes four concurrent 4000-unit refunds against a
//!   10000-unit charge let exactly two through before either has called the
//!   provider at all (`refunds.feature`, the race at the end of the file).
//!   This whole paragraph is about `reason != "duplicate"` refunds only — see
//!   below.
//! - The caller makes the provider call OUTSIDE any lock.
//! - [`complete_refund`] takes another, short lock to record the answer: on
//!   success, mark the refund `succeeded` and close the payment if it is now
//!   fully refunded; on failure, ROLL BACK the reservation, so the money the
//!   provider never actually took stops counting against the charge
//!   (`refunds.feature`'s `502`/lost-answer scenarios: `amount_refunded`
//!   reads `0` afterwards, and the same amount is refundable again).
//!
//! One `reason` changes the whole shape of both: `"duplicate"` — the
//! automatic refund of a second, unwanted charge (`spec.md`, "When the
//! customer pays twice") — is never bounded by, and never moves,
//! `amount_refunded`, and never closes the payment as `refunded`, because
//! that charge was never the order's own money to begin with. It is still a
//! real `refunds` row, still a real call to the provider, and still resent by
//! the reconciler while `pending`, exactly like any other refund — only the
//! order's own accounting is untouched by it.

use paygate_domain::{check_refund, Amount, EventType, MerchantId, PaymentStatus};
use uuid::Uuid;

use crate::db::Db;
use crate::error::{Error, Result};

use super::{
    insert_event, insert_notification, lock_attempt_by_id, lock_payment, lock_payment_by_id,
    merchant_notify_fields, MerchantContext, MerchantNotifyFacts,
};

/// What `create_refund` reserved: enough for the caller to build the
/// provider's refund request without a second query.
#[derive(Debug, Clone)]
pub struct RefundReservation {
    pub refund_id: Uuid,
    pub attempt_id: Uuid,
    pub provider_code: String,
    pub provider_trade_no: String,
    pub provider_charge_id: Option<String>,
    pub amount: Amount,
}

/// Reserve a refund against a payment, under its row lock, and open the
/// `refunds` row `pending`. `refund_id` is generated by the caller (a
/// UUIDv7) because it doubles as the number sent to the provider as ITS OWN
/// deduplication key (`spec.md`, "Refunds") — generating it here, after the
/// fact, would make a lost-answer retry mint a fresh id and lose the
/// deduplication the whole design leans on.
///
/// `attempt_id`: `None` resolves to the attempt that actually settled the
/// order (the earliest-`settled_at` `succeeded` attempt) — the ordinary,
/// merchant-initiated refund, which does not know or care which of a
/// payment's attempts was the one the provider charged. `Some(id)` refunds a
/// SPECIFIC attempt — the automatic duplicate-payment refund, which must
/// target the second (duplicate) attempt's own charge, never the first.
pub async fn create_refund(
    db: &Db,
    merchant_id: MerchantId,
    payment_id: Uuid,
    refund_id: Uuid,
    amount: Amount,
    reason: Option<&str>,
    attempt_id: Option<Uuid>,
) -> Result<RefundReservation> {
    let mut tx = db.begin().await?;

    let payment = lock_payment(&mut tx, payment_id, merchant_id)
        .await?
        .ok_or(Error::PaymentNotFound)?;

    // `reason` is the honest marker for whose money this is (the refunds
    // table itself carries it, and `duplicate_payment.feature` asserts the
    // stored row's `reason = 'duplicate'`) — deliberately preferred here over
    // inferring it from `attempt_id.is_some()`, which happens to be true for
    // this path today but is an implementation coincidence, not a statement
    // about the money.
    let is_duplicate = reason == Some("duplicate");

    // A duplicate's own refund is not drawn from the order's own budget, so
    // it is not gated by the order's own refund status either:
    // `decide()` (`repo::callbacks`) only ever produces a `Duplicate`
    // outcome once the order has already settled one way or another
    // (`Succeeded`, or — a very late second charge noticed only after the
    // merchant already gave the whole order back — `Refunded`), never
    // `Pending`. Gating this on "is the order EXACTLY `Succeeded` right
    // now", the ordinary refund's own rule, would refuse to give a
    // duplicate charge back on an order the merchant has already fully
    // refunded of its own money, leaving real money stuck at the provider
    // for a reason that has nothing to do with this charge.
    let refundable_status = if is_duplicate {
        payment.status != PaymentStatus::Pending
    } else {
        payment.status == PaymentStatus::Succeeded
    };
    if !refundable_status {
        return Err(Error::PaymentNotRefundable);
    }

    if is_duplicate {
        // A duplicate's own charge was never the order's money (`spec.md`,
        // "When the customer pays twice": "amount_refunded is untouched,
        // because that second charge was never this order's money"), so the
        // ordinary `amount - amount_refunded` bound does not apply to it —
        // bounding it that way would refuse to give the second charge back
        // once the order itself has already been fully refunded, leaving
        // real money stuck at the provider for no reason tied to the order's
        // own budget. The only thing that still has to hold is that the
        // request is a real, positive amount; the provider's own
        // deduplication on `refund_id`, and the exact amount already named
        // in this attempt's `PaymentDuplicatePaid` audit row, are what keep
        // this from ever being asked for twice or for the wrong amount.
        if amount <= 0 {
            return Err(Error::Domain(
                paygate_domain::DomainError::InvalidRefundAmount,
            ));
        }
    } else {
        check_refund(payment.amount, payment.amount_refunded, amount).map_err(|e| match e {
            paygate_domain::DomainError::RefundExceedsRemaining {
                requested,
                remaining,
            } => Error::RefundExceedsRemaining {
                requested,
                remaining,
            },
            other => Error::Domain(other),
        })?;
    }

    let attempt = match attempt_id {
        Some(id) => lock_attempt_by_id(&mut tx, id)
            .await?
            .ok_or(Error::PaymentNotFound)?,
        None => {
            let row = sqlx::query(
                "SELECT id, payment_id, provider_code, provider_trade_no, status, rtn_code, \
                        simulate_paid, failure_code, provider_charge_id, card_brand, card_last4, \
                        eci, auth_code, started_at, queried_at, settled_at \
                   FROM payment_attempts \
                  WHERE payment_id = $1 AND status = 'succeeded' \
                  ORDER BY settled_at ASC NULLS LAST, started_at ASC \
                  LIMIT 1 \
                  FOR UPDATE",
            )
            .bind(payment_id)
            .fetch_optional(&mut *tx)
            .await?;
            let row = row.ok_or(Error::PaymentNotRefundable)?;
            super::map_attempt_row(&row)?
        }
    };

    sqlx::query(
        "INSERT INTO refunds (id, payment_id, attempt_id, merchant_id, amount, status, reason) \
         VALUES ($1, $2, $3, $4, $5, 'pending', $6)",
    )
    .bind(refund_id)
    .bind(payment_id)
    .bind(attempt.id)
    .bind(merchant_id)
    .bind(amount)
    .bind(reason)
    .execute(&mut *tx)
    .await?;

    if !is_duplicate {
        // Reserve it against the ORDER's own budget — but only for a refund
        // that is actually of the order's money. A duplicate's refund must
        // never move `amount_refunded`: that column is "what the merchant
        // may still give back" (`duplicate_payment.feature`, "The duplicate
        // charge is given back..."), and the second charge was never part of
        // what the merchant was owed for the order in the first place.
        sqlx::query("UPDATE payments SET amount_refunded = amount_refunded + $1, updated_at = now() WHERE id = $2")
            .bind(amount)
            .bind(payment_id)
            .execute(&mut *tx)
            .await?;
    }

    tx.commit().await?;

    Ok(RefundReservation {
        refund_id,
        attempt_id: attempt.id,
        provider_code: attempt.provider_code,
        provider_trade_no: attempt.provider_trade_no,
        provider_charge_id: attempt.provider_charge_id,
        amount,
    })
}

/// What the provider call outside the lock came back with.
#[derive(Debug, Clone)]
pub enum RefundOutcome {
    Succeeded {
        provider_refund_id: String,
    },
    /// The provider call did not resolve at all — `PSP_TIMEOUT_MS`
    /// (`spec.md`, "Environment variables") — which alone is worth its own
    /// audit row (`ProviderCallTimedOut`); a normal, fast rejection (a
    /// `5xx`, a malformed answer) is not distinguished from it in the schema
    /// and writes none.
    Failed {
        timed_out: bool,
    },
}

/// What completing a refund left behind.
#[derive(Debug, Clone)]
pub struct RefundCompletion {
    pub payment_status: PaymentStatus,
    pub amount_refunded: Amount,
}

/// Record what the provider said about a reserved refund. See the module doc
/// for why the reservation and this completion are separate transactions.
#[allow(clippy::too_many_arguments)]
pub async fn complete_refund(
    db: &Db,
    payment_id: Uuid,
    refund_id: Uuid,
    amount: Amount,
    outcome: RefundOutcome,
    merchant: &MerchantContext,
    merchant_hash_key: &str,
    merchant_hash_iv: &str,
) -> Result<RefundCompletion> {
    let mut tx = db.begin().await?;
    let payment = lock_payment_by_id(&mut tx, payment_id)
        .await?
        .ok_or(Error::PaymentNotFound)?;

    // The reason on record is what decides whether this refund ever reserved
    // anything against the ORDER's own accounting: `create_refund` bumps
    // `amount_refunded` only for a refund that is not `duplicate` (see
    // there), so completing it — on either outcome — must undo exactly what
    // was actually reserved: nothing, for a duplicate's own refund. Read from
    // `refunds` itself (the honest marker `duplicate_payment.feature`
    // asserts on the row) rather than inferred from `attempt_id`, for the
    // same reason `create_refund` does.
    let refund_reason: Option<String> =
        sqlx::query_scalar("SELECT reason FROM refunds WHERE id = $1")
            .bind(refund_id)
            .fetch_optional(&mut *tx)
            .await?
            .flatten();
    let is_duplicate = refund_reason.as_deref() == Some("duplicate");

    match outcome {
        RefundOutcome::Succeeded { provider_refund_id } => {
            sqlx::query(
                "UPDATE refunds SET status = 'succeeded', provider_refund_id = $1 WHERE id = $2",
            )
            .bind(&provider_refund_id)
            .bind(refund_id)
            .execute(&mut *tx)
            .await?;

            // A duplicate's own settlement must never flip the ORDER to
            // `refunded` — that transition belongs only to the merchant's
            // own money coming back, and `amount_refunded` was never moved
            // for this refund in the first place, so nothing here should act
            // as if it might have reached `payment.amount`.
            if !is_duplicate {
                let now_fully_refunded = payment.amount_refunded >= payment.amount;
                if now_fully_refunded {
                    sqlx::query(
                        "UPDATE payments SET status = 'refunded', updated_at = now() WHERE id = $1",
                    )
                    .bind(payment_id)
                    .execute(&mut *tx)
                    .await?;
                }
            }

            let payload = serde_json::json!({
                "refund_id": refund_id,
                "amount": amount,
                "currency": payment.currency,
                "reference": payment.merchant_trade_no,
                "provider_refund_id": provider_refund_id,
            });
            insert_event(
                &mut tx,
                payment_id,
                payment.merchant_id,
                EventType::PaymentRefunded,
                payload,
            )
            .await?;

            // A duplicate's own automatic refund is not reported to the
            // merchant (`spec.md`, "When the customer pays twice": "The
            // merchant: told once, about the payment"). Every
            // merchant-initiated refund is.
            if !is_duplicate {
                write_refunded_notification(
                    &mut tx,
                    &payment,
                    merchant,
                    amount,
                    merchant_hash_key,
                    merchant_hash_iv,
                )
                .await?;
            }
        }
        RefundOutcome::Failed { timed_out } => {
            // Roll back the reservation: this money never actually moved.
            // There is nothing to roll back for a duplicate's own refund,
            // because `create_refund` never reserved anything against
            // `amount_refunded` for one — subtracting here regardless would
            // either take real money away from a genuine earlier refund's
            // own accounting or drive the column negative, tripping
            // `payments`'s own `CHECK (amount_refunded BETWEEN 0 AND
            // amount)`.
            if !is_duplicate {
                sqlx::query("UPDATE payments SET amount_refunded = amount_refunded - $1, updated_at = now() WHERE id = $2")
                    .bind(amount)
                    .bind(payment_id)
                    .execute(&mut *tx)
                    .await?;
            }

            if timed_out {
                let payload = serde_json::json!({
                    "refund_id": refund_id,
                    "amount": amount,
                    "currency": payment.currency,
                    "reference": payment.merchant_trade_no,
                });
                insert_event(
                    &mut tx,
                    payment_id,
                    payment.merchant_id,
                    EventType::ProviderCallTimedOut,
                    payload,
                )
                .await?;
            }
        }
    }

    let final_row: (String, Amount) =
        sqlx::query_as("SELECT status, amount_refunded FROM payments WHERE id = $1")
            .bind(payment_id)
            .fetch_one(&mut *tx)
            .await?;
    let payment_status: PaymentStatus = super::parse_enum_column("status", &final_row.0)?;

    tx.commit().await?;
    Ok(RefundCompletion {
        payment_status,
        amount_refunded: final_row.1,
    })
}

async fn write_refunded_notification(
    tx: &mut sqlx::Transaction<'_, sqlx::Postgres>,
    payment: &super::PaymentRow,
    merchant: &MerchantContext,
    amount: Amount,
    merchant_hash_key: &str,
    merchant_hash_iv: &str,
) -> Result<()> {
    let notify_facts = MerchantNotifyFacts {
        provider_merchant_id: merchant.provider_merchant_id.clone(),
        merchant_trade_no: merchant.merchant_trade_no.clone(),
        payment_id: payment.id,
        rtn_code: 1,
        rtn_msg: "refunded",
        amount,
        paid_at: chrono::Utc::now(),
    };
    let mut fields = merchant_notify_fields(&notify_facts);
    let mac =
        paygate_provider::ecpay::check_mac_value(merchant_hash_key, merchant_hash_iv, &fields);
    fields.insert("CheckMacValue".to_string(), mac);
    let payload = serde_json::to_value(&fields).unwrap_or(serde_json::Value::Null);
    insert_notification(
        tx,
        payment.id,
        merchant.merchant_id,
        &merchant.notify_url,
        payload,
    )
    .await?;
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn refund_exceeding_remaining_maps_to_the_typed_error() {
        let err = check_refund(1000, 800, 300).unwrap_err();
        let mapped = match err {
            paygate_domain::DomainError::RefundExceedsRemaining {
                requested,
                remaining,
            } => Error::RefundExceedsRemaining {
                requested,
                remaining,
            },
            other => Error::Domain(other),
        };
        match mapped {
            Error::RefundExceedsRemaining {
                requested,
                remaining,
            } => {
                assert_eq!(requested, 300);
                assert_eq!(remaining, 200);
            }
            _ => panic!("expected RefundExceedsRemaining"),
        }
    }
}
